# Generated by Django 4.2.13 on 2024-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mango',
            name='category',
            field=models.CharField(choices=[('Fazlee', 'Fazlee'), ('Langda', 'Langda'), ('Gopalbogh', 'Gopalbogh'), ('Himsagar', 'Himsagar')], max_length=20),
        ),
    ]
