# Generated by Django 4.2.13 on 2024-07-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_alter_mango_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
